# Generated by Django 5.1.6 on 2025-04-01 04:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeiAriUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cug_phone_number', models.CharField(max_length=20)),
                ('cug_email_address', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('access_list', models.TextField()),
                ('role', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TNGovtDept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=255)),
                ('level', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkGroupMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_id', models.IntegerField()),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkGroupS3Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('s3_file_url', models.URLField()),
                ('sent_by', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkTaskDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('group_id', models.IntegerField()),
                ('created_by', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('due_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkTaskPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField()),
                ('assigned_to', models.IntegerField()),
                ('assigned_by', models.IntegerField()),
                ('assigned_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkTaskReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(max_length=100, unique=True)),
                ('report_content', models.TextField()),
                ('assigned_to', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MeiAriUserBioData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('alternative_email_address', models.EmailField(max_length=254)),
                ('access_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geminiflash.meiariuser')),
            ],
        ),
        migrations.CreateModel(
            name='OTPTable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('otp', models.CharField(max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geminiflash.meiariuser')),
            ],
        ),
        migrations.CreateModel(
            name='TNGovtDeptContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cug_minister_email', models.EmailField(max_length=254)),
                ('cug_minister_phone_number', models.CharField(max_length=20)),
                ('minister_name', models.CharField(max_length=255)),
                ('stg_email', models.EmailField(max_length=254)),
                ('stg_phone_number', models.CharField(max_length=20)),
                ('stg_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geminiflash.tngovtdept')),
            ],
        ),
        migrations.CreateModel(
            name='TNGovtSubDept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_department_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geminiflash.tngovtdept')),
            ],
        ),
        migrations.CreateModel(
            name='SubDeptOfficeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_dept_office_location', models.CharField(max_length=255)),
                ('sub_dept_street_address', models.TextField()),
                ('sub_dept_district', models.CharField(max_length=255)),
                ('sub_dept_taluk', models.CharField(max_length=255)),
                ('sub_dept_access_code', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('sub_dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geminiflash.tngovtsubdept')),
            ],
        ),
        migrations.CreateModel(
            name='SubDeptDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_dept_office', models.CharField(max_length=255)),
                ('sub_dept_hod', models.CharField(max_length=255)),
                ('sub_dept_cug_email', models.EmailField(max_length=254)),
                ('sub_dept_cug_phone_number', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('sub_dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geminiflash.tngovtsubdept')),
            ],
        ),
        migrations.CreateModel(
            name='WorkGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=100, unique=True)),
                ('group_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('sub_dept_office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geminiflash.subdeptofficedetails')),
            ],
        ),
        migrations.CreateModel(
            name='WorkGroupDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_description', models.TextField()),
                ('group_photo', models.ImageField(blank=True, null=True, upload_to='group_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('work_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geminiflash.workgroup')),
            ],
        ),
        migrations.CreateModel(
            name='WorkGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('role_name', models.CharField(max_length=100)),
                ('joined_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('work_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geminiflash.workgroup')),
            ],
        ),
        migrations.CreateModel(
            name='WorkGroupAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.IntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geminiflash.workgroupmessage')),
            ],
        ),
        migrations.CreateModel(
            name='WorkGroupTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_code', models.CharField(max_length=100, unique=True)),
                ('ticket_title', models.CharField(max_length=255)),
                ('ticker_description', models.TextField()),
                ('ticket_status', models.CharField(max_length=50)),
                ('priority', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('work_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geminiflash.workgroup')),
            ],
        ),
        migrations.AddField(
            model_name='workgroupmessage',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geminiflash.workgroupticket'),
        ),
        migrations.CreateModel(
            name='WorkTaskSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collector_id', models.IntegerField()),
                ('signed_at_date', models.DateTimeField()),
                ('status', models.CharField(max_length=50)),
                ('official_name', models.CharField(max_length=255)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geminiflash.worktaskreport')),
            ],
        ),
        migrations.CreateModel(
            name='WorkTestVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified_by', models.IntegerField()),
                ('verification_status', models.CharField(max_length=50)),
                ('verification_date', models.DateTimeField()),
                ('comments', models.TextField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geminiflash.worktaskreport')),
            ],
        ),
    ]
